# Generated by Django 4.2.3 on 2023-08-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_alter_student_email_alter_teacher_email'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginsys.teacher'),
        ),
    ]
